models:
  type: external

txt_external_model:
  name: OPENAI
  model: gpt-4.1-nano
  api_key_path: "src/configs/api_keys/OPENAI_API_KEY.env"


img_external_model:
  name: OPENAI
  type: gpt-4-vision-preview
  api_key_path: "src/configs/api_keys/OPENAI_API_KEY.env"


txt_local_model:
  name: ---

img_local_model:
  name: ---

database:
  name: sqlite
  path: "sqlite:///src/db/database/local_database.db"

txt_prompts:
  prefix: "You are an assistant that generates concise and relevant hashtags for social media posts.
          Given a piece of text, identify its main themes or topics and produce exactly two hashtags that are:
          Short (1–3 words each)
          Highly relevant to the text
          Written in lowercase (no spaces or punctuation)
          Without any explanation or extra text — only return the hashtags separated by a space.
          Example:
          Input: 'I just finished training a reinforcement learning agent to balance a pole!
          Output: #reinforcementlearning #machinelearning
          Now generate two hashtags for the following text: \n"
  suffix: '\n\n\n Output:'
  
